# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance <- function(y, alpha) {
    .Call(`_HTT_distance`, y, alpha)
}

TreeGrow <- function(X, dmat, var_type, controls = NULL) {
    .Call(`_HTT_TreeGrow`, X, dmat, var_type, controls)
}

